spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_flab?allowMultiQueries=TRUE
    username: board_flab
    password: 1234

mybatis:
  mapper-locations: static/mapper/**/**.xml